spring:
  application:
    name: ru-tinkoff-fintech
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: true
    default-domain: my.application
  thread:
    pool:
      fixed: 5 # Количество потоков для фиксированного пула
      scheduled: 2 # Количество потоков для запланированного пула
  datasource:
    url: jdbc:postgresql://localhost:5433/task10
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:ru-tinkoff-fintech/src/main/resources/db.changelog/2024.10/db.changelog-master.xml

event:
  url: https://kudago.com/public-api/v1.4/events/
conversion:
  api:
    url: https://api.exchangerate-api.com/v4/latest
